version: '2'
services:
  testjhipster-app:
    image: testjhipster
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://testjhipster-postgresql:5432/testJhipster
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  testjhipster-postgresql:
    extends:
      file: postgresql.yml
      service: testjhipster-postgresql
